/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlayerConnection */

#ifndef _Included_PlayerConnection
#define _Included_PlayerConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlayerConnection
 * Method:    hello
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PlayerConnection_hello
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
